selectionSort:
	gcc main.c selectionSort.c -o prog

insertionSort:
	gcc main.c insertionSort.c -o prog

bubbleSort:
	gcc main.c bubbleSort.c -o prog

shakerSort:
	gcc main.c shakerSort.c -o prog

run:
	valgrind ./prog $(N) < $(ARQ)
