run:
	./prog $(N) $(P)
v1:
	gcc main.c qsortV1.c -o prog
v2:
	gcc main.c qsortV2.c -o prog
v3:
	gcc main.c qsortV3.c -o prog
v4:
	gcc main.c qsortV4.c -o prog
v5:
	gcc main.c qsortV5.c -o prog
v6:
	gcc main.c qsortV6.c -o prog
v7:
	gcc main.c qsortV7.c -o prog