run:
	./prog $(N) $(P)
v1:
	gcc main.c mergeV1.c -o prog
v2:
	gcc main.c mergeV2.c -o prog
v3:
	gcc main.c mergeV3.c -o prog
v4:
	gcc main.c mergeV4.c -o prog
v5:
	gcc main.c mergeV5.c -o prog
v6:
	gcc main.c mergeV6.c -o prog
v7:
	gcc main.c mergeV7.c -o prog